### ISSUE TITLE
error while running npx functions-request

### ISSUE THREAD

**Issue by 007vasy** [smartcontractkit/functions-hardhat-starter-kit#109]
hi,

I can deploy a contract, and I created a subcription easliy, but when I try to run:
`npx hardhat functions-request --network sepolia --contract 0x1Ae7F4caf34BbBaa13CFc7Ec5f835506fc807f0b --subid 57`
then I get:
```
❯ npx hardhat functions-request --network sepolia --contract 0x1Ae7F4caf34BbBaa13CFc7Ec5f835506fc807f0b --subid 57
secp256k1 unavailable, reverting to browser version
Simulating Functions request locally...

__Console log messages from sandboxed code__

__Output from sandboxed source code__
Output represented as a hex string: 0x00000000000000000000000000000000000000000000000000000000000f50ed
Decoded as a uint256: 1003757


If all 100000 callback gas is used, this request is estimated to cost 0.426465500634489687 LINK
Continue? (y) Yes / (n) No
y

Requesting new data for FunctionsConsumer contract 0x1Ae7F4caf34BbBaa13CFc7Ec5f835506fc807f0b on network sepolia
Waiting 2 blocks for transaction 0x84f976729da85d554547dcc51222d672beba615cb95e1110e5112ab84e785307 to be confirmed...

/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/@ethersproject/logger/src.ts/index.ts:269
        const error: any = new Error(message);
                           ^
Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x84f976729da85d554547dcc51222d672beba615cb95e1110e5112ab84e785307", transaction={"hash":"0x84f976729da85d554547dcc51222d672beba615cb95e1110e5112ab84e785307","type":0,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x4618B0c5A1d6957F0b9620A4504b08Ed31b22736","gasPrice":{"type":"BigNumber","hex":"0x0b44dd6400"},"gasLimit":{"type":"BigNumber","hex":"0x16e360"},"to":"0x1Ae7F4caf34BbBaa13CFc7Ec5f835506fc807f0b","value":{"type":"BigNumber","hex":"0x00"},"nonce":8,"data":"0xd22b224a00000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000560000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006a0000000000000000000000000000000000000000000000000000000000000003900000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000000004622f2f2054686973206578616d706c652073686f777320686f7720746f2063616c63756c617465206120636f6e74696e756f75736c7920636f6d706f756e64696e6720696e746572657374656420726174652e0a2f2f20546869732063616c63756c6174696f6e20776f756c642072657175697265207369676e69666963616e74206f6e2d636861696e206761732c20627574206973206561737920666f72206120646563656e7472616c697a6564206f7261636c65206e6574776f726b2e0a0a2f2f20417267756d656e74732063616e2062652070726f7669646564207768656e2061207265717565737420697320696e697461746564206f6e2d636861696e20616e64207573656420696e20746865207265717565737420736f7572636520636f64652061732073686f776e2062656c6f770a636f6e7374207072696e636970616c416d6f756e74203d207061727365496e7428617267735b345d290a636f6e73742041505954696d6573313030203d207061727365496e7428617267735b355d290a636f6e7374204150594173446563696d616c50657263656e74616765203d2041505954696d6573313030202f20313030202f203130300a0a636f6e73742074696d65496e5965617273203d2031202f203132202f2f20726570726573656e74732031206d6f6e74680a636f6e73742065756c6572734e756d626572203d20322e373138330a0a2f2f20436f6e74696e756f75736c792d636f6d706f756e64696e6720696e74657265737420666f726d756c613a2041203d2050655e287274290a636f6e737420746f74616c416d6f756e744166746572496e746572657374203d207072696e636970616c416d6f756e74202a2065756c6572734e756d626572202a2a20284150594173446563696d616c50657263656e74616765202a2074696d65496e5965617273290a0a2f2f2054686520736f7572636520636f6465204d5553542072657475726e206120427566666572206f722074686520726571756573742077696c6c2072657475726e20616e206572726f72206d6573736167650a2f2f20557365206f6e65206f662074686520666f6c6c6f77696e672066756e6374696f6e7320746f20636f6e7665727420746f20612042756666657220726570726573656e74696e672074686520726573706f6e73652062797465732074686174206172652072657475726e656420746f2074686520636c69656e7420736d61727420636f6e74726163743a0a2f2f202d2046756e6374696f6e732e656e636f646555696e743235360a2f2f202d2046756e6374696f6e732e656e636f6465496e743235360a2f2f202d2046756e6374696f6e732e656e636f6465537472696e670a2f2f204f722072657475726e206120637573746f6d2042756666657220666f72206120637573746f6d206279746520656e636f64696e670a72657475726e2046756e6374696f6e732e656e636f646555696e74323536284d6174682e726f756e6428746f74616c416d6f756e744166746572496e74657265737429290a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111432a9d448855c59279131ec8bbcf842e02b16a4e5c4c2ceaa034cf952623f76ebc3bf93fc03c53fc857b68c21a93dee6f5782e21bf8823081fe0316db94dc0eadadfddcf41178016d930bd93fad5052bd8753b20f7e0876d5bc02968affd6f2f5780989ebf66a84bd4d3a46a88892400576b1583b406e914d2be8af662dbe34447bd9e899bd98538070c8191afd76aeae4c3d48b411274397347a3d44a7af76e8c1a42b7f07a916ed073bc9e652af68222b4565d474cb43eb7bc13d8ddd9c2c565bc23169ca87be875c6ede1fc331243cb49644a6c0551c5deb3415540b49fd4650d52c35547545d746c0859904f9bf67af6bcfbeee4279c28a38afa013065d27c31853cb3418d8659eb778eb414778e2f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000131000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007626974636f696e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b6274632d626974636f696e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000362746300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007313030303030300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000033435300000000000000000000000000000000000000000000000000000000000","r":"0xb2c49b4ec653151dbc272b02a8158076bca45c8f1efa37631bf65a4f6c83706c","s":"0x22689e70531ee85988f198026af642709553831a1366a9f44f155149626f5c9c","v":22310258,"creates":null,"chainId":11155111}, receipt={"to":"0x1Ae7F4caf34BbBaa13CFc7Ec5f835506fc807f0b","from":"0x4618B0c5A1d6957F0b9620A4504b08Ed31b22736","contractAddress":null,"transactionIndex":1,"gasUsed":{"type":"BigNumber","hex":"0x029fde"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x597ac7823dccb6b69c7fb18482b12b048fc6d3c43c930f36500d31e80d8060c0","transactionHash":"0x84f976729da85d554547dcc51222d672beba615cb95e1110e5112ab84e785307","logs":[],"blockNumber":3024050,"confirmations":2,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x02f9e6"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x0b44dd6400"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1549:24)
    at step (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
```

**Comment by 007vasy** [comment]
@KuphJr?

**Comment by 007vasy** [comment]
fyi mumbai worked

**Comment by BaldwinCepeda** [comment]
try over shooting the gas with --gaslimit

**Comment by KuphJr** [comment]
The issue ended up being a lack of funds in the subscription for Sepolia.

If anyone encounters this issue in the future, the increased gas costs on Sepolia when compared to Mumbai means that more LINK is required to pay for requests.

The tooling should detect a insufficient subscription balance and report an error, but a gas spike may occur in between the time the request cost is estimated versus when it is initiated on-chain.  Ensure your subscription is sufficiently funded before retrying.
