### ISSUE TITLE
Unable to use `functions-sub-accept` 

### ISSUE THREAD

**Issue by virajpatva** [smartcontractkit/functions-hardhat-starter-kit#194]
I create a sub from account 1 than created a transfer request and than changed private key in env to account 2 and tried the command but got the following error : 

```
Error: This command requires a second wallet's private key to be made available in networks.js
    at SimpleTaskDefinition.action (/home/viraj/Documents/Blockchain/functions-hardhat-starter-kit/tasks/Functions-billing/accept.js:10:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Environment._runTaskDefinition (/home/viraj/Documents/Blockchain/functions-hardhat-starter-kit/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at Environment.run (/home/viraj/Documents/Blockchain/functions-hardhat-starter-kit/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at main (/home/viraj/Documents/Blockchain/functions-hardhat-starter-kit/node_modules/hardhat/src/internal/cli/cli.ts:280:7)```

**Comment by virajpatva** [comment]
@bolekk @KuphJr @justinkaseman

**Comment by virajpatva** [comment]
The issue is resolved once I updated the SECOND_PRIVATE_KEY. Just a suggestion from my end we can update about it in readme.

**Comment by KuphJr** [comment]
@virajpatva Thanks! What is your recommended change to the README to better inform future users about the neet to set the `SECOND_PRIVATE_KEY`?

**Comment by virajpatva** [comment]
Yes, we need to inform user about the need to set SECOND_PRIVATE_KEY , I will raise PR soon

**Comment by zeuslawyer** [comment]
@virajpatva @KuphJr 
https://github.com/smartcontractkit/functions-hardhat-starter-kit/blob/main/tasks/Functions-billing/accept.js#L12

instruction is to setup second key is here on this line but should be in README too.
