### ISSUE TITLE
functions-sub-cancel not working on Polygon Mumbai

### ISSUE THREAD

**Issue by zeuslawyer** [smartcontractkit/functions-hardhat-starter-kit#30]
@KuphJr @justinkaseman 

Subscription details are:
```
Subscription 23 owner: 0x208AA722Aca42399eaC5192EE778e4D42f4E5De3
Balance: 0.000000091 LINK
1 authorized consumer contract:
[ '0x4CA9b22A38dC98Af6195E595FE8200aEBf833A0C' ]
```

My contract address is verified.

When I try and run `yhh functions-sub-cancel --network mumbai --subid 23` it works all the way to line 50 of `cancel.js` where we console out the number of confirmations we are waiting for.

And then it fails with the following output in console (and here is the [polygonscan tx hash data](https://mumbai.polygonscan.com/tx/0x8ba5c009dc40d4f51b5347c7b844deb74be7ed8f622d9ee0fb9942b107a95649)).

I've seen `CALL_EXCEPTION` before where my address wasn't whitelisted, but that's not the case as I've run other commands. All the other commands work except for this.

```
Waiting 2 blocks for transaction 0x8ba5c009dc40d4f51b5347c7b844deb74be7ed8f622d9ee0fb9942b107a95649 to be confirmed...

An unexpected error occurred:

Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x8ba5c009dc40d4f51b5347c7b844deb74be7ed8f622d9ee0fb9942b107a95649", transaction={"hash":"0x8ba5c009dc40d4f51b5347c7b844deb74be7ed8f622d9ee0fb9942b107a95649","type":2,"accessList":[],"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x208AA722Aca42399eaC5192EE778e4D42f4E5De3","gasPrice":{"type":"BigNumber","hex":"0x59682f12"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f12"},"gasLimit":{"type":"BigNumber","hex":"0x1eddd8"},"to":"0xE7e4882E6cc98b4c20A5155ca83A18C85aaBfCe6","value":{"type":"BigNumber","hex":"0x00"},"nonce":59,"data":"0xd7ae1d300000000000000000000000000000000000000000000000000000000000000017000000000000000000000000208aa722aca42399eac5192ee778e4d42f4e5de3","r":"0xd58d55d4519718a39c48e5fc03251bd16968e99e786c294dd271a5f10ae63ac1","s":"0x3178dd6ed593ab840b293b98c967d05c63a16dc95fa0fe90c1f381f07e9983cf","v":0,"creates":null,"chainId":80001}, receipt={"to":"0xE7e4882E6cc98b4c20A5155ca83A18C85aaBfCe6","from":"0x208AA722Aca42399eaC5192EE778e4D42f4E5De3","contractAddress":null,"transactionIndex":2,"gasUsed":{"type":"BigNumber","hex":"0xa813"},"logsBloom":"0x00000000000000000000000000000000000000080000000000000010000000000000000000000020000000008000000000008000000000000000000000000000000000000000000000000000000000800000000002000000000100000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000004000000000000000000001000000000000000000000000000000100000001000000000000000000000000000000000000000000000000000000000000000100000","blockHash":"0xafd003259728121c69a1d5bc12f7bb8b60659cbf88de4bb6c3f8bcf3640780fb","transactionHash":"0x8ba5c009dc40d4f51b5347c7b844deb74be7ed8f622d9ee0fb9942b107a95649","logs":[{"transactionIndex":2,"blockNumber":31009926,"transactionHash":"0x8ba5c009dc40d4f51b5347c7b844deb74be7ed8f622d9ee0fb9942b107a95649","address":"0x0000000000000000000000000000000000001010","topics":["0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63","0x0000000000000000000000000000000000000000000000000000000000001010","0x000000000000000000000000208aa722aca42399eac5192ee778e4d42f4e5de3","0x000000000000000000000000f903ba9e006193c1527bfbe65fe2123704ea3f99"],"data":"0x00000000000000000000000000000000000000000000000000003ab301937d0000000000000000000000000000000000000000000000000002420d11f14a39e80000000000000000000000000000000000000000000009d98d2832e49b77de620000000000000000000000000000000000000000000000000241d25eefb6bce80000000000000000000000000000000000000000000009d98d286d979d0b5b62","logIndex":6,"blockHash":"0xafd003259728121c69a1d5bc12f7bb8b60659cbf88de4bb6c3f8bcf3640780fb"}],"blockNumber":31009926,"confirmations":3,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x05e7d8"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x59682f0f"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/Users/zubinpratap/Documents/code/ocr-on-demand/demor2-billing-tooling/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/zubinpratap/Documents/code/ocr-on-demand/demor2-billing-tooling/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/Users/zubinpratap/Documents/code/ocr-on-demand/demor2-billing-tooling/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1549:24)
    at step (/Users/zubinpratap/Documents/code/ocr-on-demand/demor2-billing-tooling/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/Users/zubinpratap/Documents/code/ocr-on-demand/demor2-billing-tooling/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/Users/zubinpratap/Documents/code/ocr-on-demand/demor2-billing-tooling/node_modules/@ethersproject/providers/lib/base-provider.js:20:58) {
  reason: 'transaction failed',
  code: 'CALL_EXCEPTION',
  transactionHash: '0x8ba5c009dc40d4f51b5347c7b844deb74be7ed8f622d9ee0fb9942b107a95649',
  transaction: {
    hash: '0x8ba5c009dc40d4f51b5347c7b844deb74be7ed8f622d9ee0fb9942b107a95649',
    type: 2,
    accessList: [],
    blockHash: null,
    blockNumber: null,
    transactionIndex: null,
    confirmations: 0,
    from: '0x208AA722Aca42399eaC5192EE778e4D42f4E5De3',
    gasPrice: BigNumber { value: "1500000018" },
    maxPriorityFeePerGas: BigNumber { value: "1500000000" },
    maxFeePerGas: BigNumber { value: "1500000018" },
    gasLimit: BigNumber { value: "2022872" },
    to: '0xE7e4882E6cc98b4c20A5155ca83A18C85aaBfCe6',
    value: BigNumber { value: "0" },
    nonce: 59,
    data: '0xd7ae1d300000000000000000000000000000000000000000000000000000000000000017000000000000000000000000208aa722aca42399eac5192ee778e4d42f4e5de3',
    r: '0xd58d55d4519718a39c48e5fc03251bd16968e99e786c294dd271a5f10ae63ac1',
    s: '0x3178dd6ed593ab840b293b98c967d05c63a16dc95fa0fe90c1f381f07e9983cf',
    v: 0,
    creates: null,
    chainId: 80001,
    wait: [Function (anonymous)]
  },
  receipt: {
    to: '0xE7e4882E6cc98b4c20A5155ca83A18C85aaBfCe6',
    from: '0x208AA722Aca42399eaC5192EE778e4D42f4E5De3',
    contractAddress: null,
    transactionIndex: 2,
    gasUsed: BigNumber { value: "43027" },
    logsBloom: '0x00000000000000000000000000000000000000080000000000000010000000000000000000000020000000008000000000008000000000000000000000000000000000000000000000000000000000800000000002000000000100000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000004000000000000000000001000000000000000000000000000000100000001000000000000000000000000000000000000000000000000000000000000000100000',
    blockHash: '0xafd003259728121c69a1d5bc12f7bb8b60659cbf88de4bb6c3f8bcf3640780fb',
    transactionHash: '0x8ba5c009dc40d4f51b5347c7b844deb74be7ed8f622d9ee0fb9942b107a95649',
    logs: [ [Object] ],
    blockNumber: 31009926,
    confirmations: 3,
    cumulativeGasUsed: BigNumber { value: "387032" },
    effectiveGasPrice: BigNumber { value: "1500000015" },
    status: 0,
    type: 2,
    byzantium: true
  }
}
error Command failed with exit code 1.
```

**Comment by zeuslawyer** [comment]
Tried this out from Remix just to see if i can spot any other error clues and only got this.  It fails in preflight -- before metamask even asks to confirm the transaction.

Error messages in Metamask console are:

```
transact to FunctionsBillingRegistry.cancelSubscription pending ... 
transact to FunctionsBillingRegistry.cancelSubscription errored: Internal JSON-RPC error.
{
  "code": 3,
  "data": "0xb42f66e8",
  "message": "execution reverted"
}
```

**Comment by bolekk** [comment]
Fixed now. Closing.
