### ISSUE TITLE
function simulation error

### ISSUE THREAD

**Issue by 007vasy** [smartcontractkit/functions-hardhat-starter-kit#87]
hi,

I am trying to run
```npx hardhat function-simulate``` on an unchanged repo
and I am getting:

```
Duplicate definition of Transfer (Transfer(address,address,uint256,bytes), Transfer(address,address,uint256))
Error: Transaction reverted: function call to a non-contract account
    at FunctionsBillingRegistry.getFeedData (contracts/dev/functions/FunctionsBillingRegistry.sol:517)
    at FunctionsBillingRegistry.estimateCost (contracts/dev/functions/FunctionsBillingRegistry.sol:289)
    at FunctionsBillingRegistry.startBilling (contracts/dev/functions/FunctionsBillingRegistry.sol:334)
    at FunctionsOracle.sendRequest (contracts/dev/functions/FunctionsOracle.sol:172)
    at FunctionsConsumer.sendRequest (contracts/dev/functions/FunctionsClient.sol:63)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatNode._mineBlockWithPendingTxs (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1802:23)
    at HardhatNode.mineBlock (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:491:16)
    at EthModule._sendTransactionAndReturnHash (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)
    at HardhatNetworkProvider.request (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at EthersProviderWrapper.send (/Users/benvass/Projects/functions-hardhat-starter-kit/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

tested on:
* Mac M1 
  * node: 18.14.0
  * npm: 9.3.1
  * hardhat: 2.12.0
* Ubuntu (22.04.1) 
  * node: 18.14.0
  * npm: 9.3.1
  * hardhat: 2.12.0

I could deploy a contract to **_sepolia_**

let me know if I am just dumb or I am just missing something

**Comment by 007vasy** [comment]
(I downgraded from node19 it did not worked either and I was getting hardhat errors)

**Comment by KuphJr** [comment]
I believe this issue is because we are still setting up the DON & contracts for Sepolia.  Sepolia will be supported very soon before an official launch announcement.

Can you try setting the RPC URL for Goerli or Mumbai, unsetting Sepolia and run the command again?

**Comment by 007vasy** [comment]
@KuphJr what are the prerequisite steps for running 'npx hardhat function-simulate'?

I deployed the example contract to goerli as well, but, I am getting the same error

shouldn't the simulation be able to run without any deployment?

**Comment by KuphJr** [comment]
I just cloned a fresh repo.  All I did was run `npm install`, set the RPC URL (I set mine for mumbai) and set my wallet PRIVATE_KEY env vars.  When I ran `npx hardhat functions-simulate`, I was unable to recreate.

**Comment by 007vasy** [comment]
thanks for the help, I leave this here until it get's fixed
(the problem was that hardhat tries to use dummy values even if some of them are set)

**_not working_** `.env`:
```
MUMBAI_RPC_URL="https://polygon-mumbai.g.alchemy.com/v2/ExampleKey"
GOERLI_RPC_URL="https://goerli.infura.io/v3/<redacted>"
SEPOLIA_RPC_URL="https://sepolia.infura.io/v3/ExampleKey"
PRIVATE_KEY="<redacted>"
COINMARKETCAP_API_KEY="CoinMarketCap API key (Get a free one: https://coinmarketcap.com/api/)"
ETHERSCAN_API_KEY="<redacted>"
POLYGONSCAN_API_KEY="POLYGONSCAN API key (Get a free one: https://polygonscan.com/)"
```

**working_** `.env`:
```
GOERLI_RPC_URL="https://goerli.infura.io/v3/<redacted>"
PRIVATE_KEY="<redacted>"
ETHERSCAN_API_KEY="<redacted>"
```

**Comment by KuphJr** [comment]
This issue is resolved by this PR: https://github.com/smartcontractkit/functions-hardhat-starter-kit/pull/89
